/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhanvien;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class NhanVienFrame extends javax.swing.JFrame {

    DefaultTableModel tableModel; //Tạo bảng
    List<NhanVien> nhanvienList = new ArrayList<>(); //Tạo danh sách 

    public NhanVienFrame() {
        initComponents();
        tableModel = (DefaultTableModel) tbNhanvien.getModel(); //Gán cho bảng vừa tạo model bảng đã tạo trước đó
        showNhanVien();
    }

    private void showNhanVien() { //hiển thị tất cả đối tượng trong danh sách
        nhanvienList = NhanVienModify.findAll(); // gán tất cả đối tượng trong database vào danh sách đã tạo

        tableModel.setRowCount(0); //xóa hết các đối tượng trong bảng

        //Hiển thị các đối tượng vừa thêm vào
        nhanvienList.forEach((nhanvien) -> {
            tableModel.addRow(new Object[]{nhanvien.getId(), nhanvien.getFullname(),
                nhanvien.getGender(), nhanvien.getAge(), nhanvien.getPosition(),
                nhanvien.getEmail(), nhanvien.getPhoneNumber(), nhanvien.getSalary(), nhanvien.getBonus()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        cbPosition = new javax.swing.JComboBox<>();
        cbAge = new javax.swing.JComboBox<>();
        txtPhoneNumber = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBonus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanvien = new javax.swing.JTable();
        btUpdate = new javax.swing.JButton();
        btSum = new javax.swing.JButton();
        btReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập thông tin"));

        jLabel1.setText("Họ Tên:");

        jLabel2.setText("Giới tính:");

        jLabel3.setText("Tuổi:");

        jLabel4.setText("Vị trí:");

        jLabel5.setText("Email:");

        jLabel6.setText("SĐT:");

        jLabel7.setText("Lương:");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Nam", "Nữ" }));

        cbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Nhân viên", "Bảo vệ", "Quản lý", "Thư ký", "Giám đốc" }));

        cbAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99+" }));

        jLabel8.setText("$");

        jLabel9.setText("Bonus:");

        jLabel10.setText("$");

        jLabel11.setText("ID:");

        lbID.setText("***");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel8)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(229, 229, 229)
                                        .addComponent(jLabel11)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbID))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lbID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSave.setText("Thêm");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btRefresh.setText("Làm mới");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        btDelete.setText("Xóa");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btFind.setText("Tìm tên");
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        tbNhanvien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ tên", "Giới tính", "Tuổi", "VỊ trí", "Email", "SĐT", "Lương", "Bonus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanvien);

        btUpdate.setText("Cập nhật");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btSum.setText("Tính lương");
        btSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSumActionPerformed(evt);
            }
        });

        btReturn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btReturn.setText("Quay lại");
        btReturn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btSave)
                                .addGap(18, 18, 18)
                                .addComponent(btRefresh)
                                .addGap(18, 18, 18)
                                .addComponent(btDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btFind)
                                .addGap(18, 18, 18)
                                .addComponent(btUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btSum))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btRefresh)
                    .addComponent(btDelete)
                    .addComponent(btFind)
                    .addComponent(btUpdate)
                    .addComponent(btSum))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        lbID.setText("**");
        txtFullname.setText("");
        txtPhoneNumber.setText("");
        txtEmail.setText("");
        txtSalary.setText("");
        cbAge.setSelectedIndex(0);
        cbGender.setSelectedIndex(0);
        cbPosition.setSelectedIndex(0);
        txtBonus.setText("");
        tableModel.setRowCount(0);
        showNhanVien();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        //Khởi tạo các biến lưu trữ
        String fullname = txtFullname.getText();
        String gender = cbGender.getSelectedItem().toString();
        String age = cbAge.getSelectedItem().toString();
        String position = cbPosition.getSelectedItem().toString();
        String email = txtEmail.getText();
        String phone_number = txtPhoneNumber.getText();
        int salary = Integer.parseInt(txtSalary.getText());
        int bonus = Integer.parseInt(txtBonus.getText());
        
        //Khởi tạo 1 đối tượng chứa các biến lưu trữ
        NhanVien nv = new NhanVien(fullname, gender, email, phone_number, position, age, salary, bonus);
        
        NhanVienModify.insert(nv); //Thêm đối tượng vào danh sách

        showNhanVien(); //Hiển thị thông tin sau khi đã thêm đối tượng
    }//GEN-LAST:event_btSaveActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed

        int selectedIndex = tbNhanvien.getSelectedRow(); // khởi tạo biến để chọn hàng trong bảng

        if (selectedIndex >= 0) { //nếu như có thành phần trong bảng được chọn

            NhanVien nv = nhanvienList.get(selectedIndex); // khởi tạo giá trị lưu trữ biến đã chọn

            //tạo confirm dialog
            int option = JOptionPane.showConfirmDialog(this, "Xác nhận xóa?");
            System.out.println(option);
            if (option == 0) {
                NhanVienModify.delete(nv.getId()); //xóa dữ liệu
            }
            showNhanVien();
        }
        txtFullname.setText("");
        txtPhoneNumber.setText("");
        txtEmail.setText("");
        txtSalary.setText("");
        cbAge.setSelectedIndex(0);
        cbGender.setSelectedIndex(0);
        cbPosition.setSelectedIndex(0);
        txtBonus.setText("");
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        String input = JOptionPane.showInputDialog("Tìm tên"); // tạo input dialog để tìm kiếm theo tên

        if (input != null && input.length() >= 0) {
            nhanvienList = NhanVienModify.findByFullname(input); // tìm kiếm các đối tượng có tên đã nhập

            tableModel.setRowCount(0); // xóa lữ liệu trong bảng

            // thêm các đối tượng vừa tìm kiếm vào bảng
            nhanvienList.forEach((nhanvien) -> {
                tableModel.addRow(new Object[]{tableModel.getRowCount() + 1, nhanvien.getFullname(),
                    nhanvien.getGender(), nhanvien.getAge(), nhanvien.getPosition(),
                    nhanvien.getEmail(), nhanvien.getPhoneNumber(), nhanvien.getBonus()});
            });
        } else {
            showNhanVien();
        }
        
    }//GEN-LAST:event_btFindActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        int selectedRow = tbNhanvien.getSelectedRow();
        if(selectedRow>=0){
            int id = (int) tbNhanvien.getValueAt(selectedRow, 0);
            for (NhanVien nv : nhanvienList) {
                if(lbID.equals(Integer.toString(nv.getId()))){
                    nv.setFullname(txtFullname.getText());
                    nv.setGender(cbGender.getSelectedItem().toString());
                    nv.setAge(cbAge.getSelectedItem().toString());
                    nv.setPosition(cbPosition.getSelectedItem().toString());
                    nv.setEmail(txtEmail.getText());
                    nv.setPhoneNumber(txtPhoneNumber.getText());
                    nv.setSalary(Integer.parseInt(txtSalary.getText()));
                    nv.setBonus(Integer.parseInt(txtBonus.getText()));
                    NhanVienModify.update(nv);
                    break;

                }
                showNhanVien();
            }
        }
        
    }//GEN-LAST:event_btUpdateActionPerformed

    private void tbNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanvienMouseClicked
        int selectedRow = tbNhanvien.getSelectedRow();
        if(selectedRow>=0){
            String fullname = (String) tbNhanvien.getValueAt(selectedRow, 1);
            
            for(NhanVien nv : nhanvienList){
                if(fullname.equals(nv.getFullname())){
                    lbID.setText(Integer.toString(nv.getId()));
                    txtFullname.setText(nv.getFullname());
                    cbGender.setSelectedItem(nv.getGender());
                    cbAge.setSelectedItem(nv.getAge());
                    cbPosition.setSelectedItem(nv.getPosition());
                    txtEmail.setText(nv.getEmail());
                    txtPhoneNumber.setText(nv.getPhoneNumber());
                    txtSalary.setText(Integer.toString(nv.getSalary()));
                    txtBonus.setText(Integer.toString(nv.getBonus()));
                    break;
                }
            }
            
        }
    }//GEN-LAST:event_tbNhanvienMouseClicked

    private void btSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumActionPerformed
        
        int selectedRow = tbNhanvien.getSelectedRow();
        if(selectedRow>=0){
            
            String fullname = (String) tbNhanvien.getValueAt(selectedRow, 1);
            int salary = (int) tbNhanvien.getValueAt(selectedRow, 7);
            int bonus = (int) tbNhanvien.getValueAt(selectedRow, 8);
            
            for(NhanVien nv : nhanvienList){
                if(fullname.equals(nv.getFullname())){
                    
                    int sum = salary + bonus;
                    JOptionPane.showMessageDialog(this, "Tổng lương của "+fullname+" là "+sum+"$");
                    break;
                }
            }
            
            
//            String fullname = txtFullname.getText();
//            int salary = Integer.parseInt(txtSalary.getText());
//            int bonus = Integer.parseInt(txtBonus.getText());
//            int sum = salary + bonus;
//            JOptionPane.showMessageDialog(this, "Tổng lương của "+fullname+" là "+sum+"$");
        }
        
        
        
        
    }//GEN-LAST:event_btSumActionPerformed

    private void btReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReturnActionPerformed
        GiaoDienChinh giaodien = new GiaoDienChinh();
        giaodien.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btFind;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btReturn;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSum;
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox<String> cbAge;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbID;
    private javax.swing.JTable tbNhanvien;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
